### ISSUE TITLE
Split EventStore*Connection interfaces

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-client#6]
Based on the questions in the chat: https://gitter.im/prooph/improoph?at=5b67641a6d45752f989370e8

I'm wondering if we can split the Connection interfaces and define smaller scopes like reading from streams, writing to streams and subscription api.

My idea is that if we have a subset of the methods defined in a smaller interface that is used by the AggregateRepository we could use composition for Snapshotter, Upcaster, Publisher instead of the current plugin system.

Something like this:

```php
$connection = new UpcastingConnection(
  $upcaster,
  new SnapshotConnection(
    $snapshotter,
    new PublishingConnection(
      $publisher,
      new EventStoreConnection($connectionSettings)
    )    
  )
);

$repository = new AggregateRepository($connection);
```

**Comment by prolic** [comment]
@codeliner from your code example, I can't know which interface is implemented on which connection implementation here.

About `PublishingConnection` - I don't think it's a good idea to have an event store connection being responsible to publish events on the message bus.

The setup looks strange, what if I change the order, f.e. inject UpcastingConnection into SnapshotConnection instead the other way around? Will it break?

I think from an end user perspective it looks much easier to setup like this:

```
$repository = new AggregateRepository($connection, $upcaster, $snapshotter, $publisher);
```

or maybe this:

```
$plugins[] = $upcaster;
$plugins[] = $snapshotter;
$plugins[] = $publisher;
$repository = new AggregateRepository($connection, $plugins);
```

**Comment by codeliner** [comment]
@prolic it is always the same interface. The real connection gets decorated by connection implementations that implement the same interface, add their specific functionality and then call the parent method.

You can of course change the order. It's like a middleware pipe.

But ok, if you don't like it we need to find another way. The thing is moving upcasters and metadata enricher to the aggregate repository is wrong IMHO. You would need to pass the same plugins to each repository and prooph/event-sourcing is not always used. It is a separate package. micro for example don't use it. So we would need to create another plugin system for micro :(

**Comment by prolic** [comment]
Micro has publisher as callback injected, metadata enricher is part of the
aggregate definition, upcasting is missing, snapshot store is in
buildCommandDispatcher. So except upcaster, micro is already done.

On Aug 7, 2018 00:49, "Alexander Miertsch" <notifications@github.com> wrote:

@prolic <https://github.com/prolic> it is always the same interface. The
real connection gets decorated by connection implementations that implement
the same interface, add their specific functionality and then call the
parent method.

You can of course change the order. It's like a middleware pipe.

But ok, if you don't like it we need to find another way. The thing is
moving upcasters and metadata enricher to the aggregate repository is wrong
IMHO. You would need to pass the same plugins to each repository and
prooph/event-sourcing is not always used. It is a separate package. micro
for example don't use it. So we would need to create another plugin system
for micro :(

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/prooph/event-store-client/issues/6#issuecomment-410774142>,
or mute the thread

**Comment by codeliner** [comment]
micro was just an example. Good that most parts are covered but does not change the main issue that the aggregate repository is not responsible for a full blown plugin system. the event store is the central component and should provide the hooks. SnapshotStore is the only exception because it provides aggregate snapshots. Upcaster, MetadataEnricher, Publisher all deal with the events written to or read from the event store no matter where they come from

**Comment by prolic** [comment]
So maybe wrap the event store with "something" that has plugins? Like the ActionEventEmitterEventStore wrapper from v7

**Comment by codeliner** [comment]
yeah, that sounds good :+1:
