### ISSUE TITLE
Protobuf dependency

### ISSUE THREAD

**Issue by gitomato** [prooph/event-store-client#87]
Thanks for your work.

I saw that Protobuf version has been downgraded from v3 to v2. What is the reason?

Also, do you plan to make protobuf optional so we can use another strategy (for example, a pure PHP userland alternative)?

**Comment by enumag** [comment]
IIRC the reason is that protobuf v3 doesn't support nullable fields.

**Comment by prolic** [comment]
The problem is server-side on the eventstore. But with the latest release they fixed this behaviour so going back to protobuf 3 from google is an option again. Need to check this, takes a little time.

By the way: Is there a pure PHP userland alternative anyway? I don't think it's worth the effort, as we would need to wrap all autogenerated classes, allegro protobuf and google protobuf have already a different interface.

**Comment by gitomato** [comment]
Thanks for your answers. 
Actually I was thinking of another serializer instead of Protobuf (native Json for example).

**Comment by prolic** [comment]
No way. This protobuf is the protocol used to communicate with the server. You can't simply wish for another implementation on the server side.
You can use http client to communicate via http api though.
